### PR TITLE
issue #7 replace getMemory() with os.totalmem()

### PR DESCRIPTION
**Pull request by adrianmarinwork**
issue #7 replace getMemory() with os.totalmem()

I've added two different formats in order that you chose how you want to display the memory.
The formatedMemory value in some remote cases could have problems, like really low memory.

### CODE REVIEW

**Comment by toddmcintire** [comment]
The ```formattedMemory``` one looks super nice! But out of curiosity does your system display the commas with periods or is the period in ```memory.split('.')[0]``` a typo?

**Comment by adrianmarinwork** [comment]
It's because the string that the native method `.toLocaleString()` returns, I suppose that it takes into account your location, because depending on Europe or America the punctuation it's different.
As you may know, in Europe the miller values go with the periods (".") and the decimals with commas, and the other way around in Ameria.
That's the reason.

**Comment by toddmcintire** [comment]
That's interesting, I actually didn't know that! This might cause issues if we can't guarantee the locale beforehand. A math based solution like I attempted in my [branch](https://github.com/toddmcintire/jsfetch/tree/memory) might be an option. 
Another idea could be to see if we can detect if the string contains a ```.``` or a ```,``` and then use it again in the split?

**Comment by adrianmarinwork** [comment]
Yeah to make sure that you don't run into any problems you could check if the string has the `.` or `,` with something like this:
`let punctuationSymbol = memory.includes('.') ? '.' : ',';`
`let formattedMemory = memory.split(punctuationSymbol)[0]`;
The math based solution of your branch could be a solution too! You can use the one that you prefer.
Also, I prefer the math solution.

**Review by toddmcintire — APPROVED** [review]

**Pull request merged**
