### PR TITLE
Issue #6 Windows logo added

### PR DESCRIPTION
**Pull request by colindaviddick**

### CODE REVIEW

**Comment by toddmcintire** [comment]
@colindaviddick if you push any commits to the main branch on your fork of the project it will update the pull request. This makes it easier to change any errors on a pull request without having to close and open a new one. Hope that helps!

**Comment by colindaviddick** [comment]
Great, that's a lot easier, I think it should be good now?

**Comment by toddmcintire** [comment]
Could you please change the ```windows``` to ```win32```, NodeJS's ```os.platform()``` returns ```win32``` for windows platforms. Other than that it looks good!

**Review by toddmcintire — APPROVED** [review]
Looks good, Thanks for all the amazing work!😃

**Pull request merged**
